modLoader="javafml"
loaderVersion="[34,)"
license="GNU GPLv3"
[[mods]]
modId="veinminer"
version="${file.jarVersion}"
displayName="Vein Miner"
authors="Nix"
description='''
This is a mod includes vein generators and miners.
'''